name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Use Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build the app
        run: |
          xcodebuild \
           -project action.xcodeproj \
           -scheme action \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator' \
           build

